# _fsapp_surface.pyi
"""Typing stubs for the `_fsapp_surface` C extension."""

def create(size: tuple[int, int], special: int | None = None) -> object: ...

# def create() -> object: ...
# def add_message(channel: object, type: int, data: str) -> None: ...
