# _fsemu_inputport.pyi
"""Typing stubs for the `_fsemu_inputport` C extension."""

def new() -> object: ...
def set_name(port: object, name: str) -> None: ...
def get_instance_id(port: object) -> int: ...
def set_device_by_index(port: object, index: int) -> None: ...
def set_device_by_type_and_instance_id(port: object, type: int, instance_id: int) -> None: ...
