#!/bin/sh
set -e

#!/bin/sh
set -e

case "`pwd`" in
    *-private)
        exec ../fs-uae-launcher-private/fs-uae-launcher "$@"
    ;;
    *)
        exec ../fs-uae-launcher/fs-uae-launcher "$@"
    ;;
esac
