# Automatically generated by Makefile.py

CC = gcc
CXX = g++
CFLAGS = -g -O2
CXXFLAGS = -g -O2
CPPFLAGS = 
LDFLAGS = 
LIBS = -ldl 

AM_CFLAGS =
AM_CFLAGS += -I. -Isrc/od-fs -Isrc/od-fs/include
AM_CFLAGS += -Isrc/include -Igen -Isrc/jit -Isrc
AM_CFLAGS += -Ilibfsemu/include -Ilibfsemu/src/lua
AM_CFLAGS += -I/usr/include/freetype2  
AM_CFLAGS += -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  
AM_CFLAGS += -DLUA_USE_POSIX
AM_CFLAGS += -pthread -I/usr/include/mirclient -I/usr/include/mircommon  
AM_CFLAGS +=  
AM_CFLAGS += -I/usr/include/libdrm  
# AM_CFLAGS += @OS_CFLAGS@
AM_CFLAGS += -I/usr/include/libpng12  
AM_CFLAGS += -D_REENTRANT -I/usr/include/SDL2  
# AM_CFLAGS += @X11_CFLAGS@
AM_CFLAGS +=  

AM_CXXFLAGS := $(AM_CFLAGS)
AM_CFLAGS += -std=gnu99

AM_CPPFLAGS = -DHAVE_CONFIG_H -DLINUX -DFSUAE -DFSEMU

AM_LIBS =
AM_LIBS += -lfreetype  
AM_LIBS += -pthread -lgthread-2.0 -lglib-2.0  
# AM_LIBS += -lmirclient -lmirprotobuf -lprotobuf  
AM_LIBS += -lopenal  
AM_LIBS += -lGLU -lGL  
# AM_LIBS += @OS_LIBS@
AM_LIBS += -lpng12  
AM_LIBS += -lSDL2  
AM_LIBS += -lX11
AM_LIBS += -lz  

all: fs-uae-device-helper fs-uae

gen/blit.h: gen/genblitter
	gen/genblitter i > gen/blit.h

gen/blitfunc.cpp: gen/genblitter gen/blitfunc.h
	gen/genblitter f > gen/blitfunc.cpp

gen/blitfunc.h: gen/genblitter
	gen/genblitter h > gen/blitfunc.h

gen/blittable.cpp: gen/genblitter gen/blitfunc.h
	gen/genblitter t > gen/blittable.cpp

gen/compemu.cpp: gen/gencomp
	mkdir -p `dirname $@`
	gen/gencomp

gen/compstbl.cpp: gen/compemu.cpp

gen/comptbl.h: gen/compemu.cpp

gen/cpudefs.cpp: gen/build68k src/table68k
	./gen/build68k < src/table68k > gen/cpudefs.cpp
	# python util/fix_tchar.py gen/cpudefs.cpp

gen/cpuemu_0.cpp: gen/gencpu
	cd gen && ./gencpu --optimized-flags

gen/cpuemu_11.cpp: gen/cpuemu_0.cpp

gen/cpuemu_13.cpp: gen/cpuemu_0.cpp

gen/cpuemu_20.cpp: gen/cpuemu_0.cpp

gen/cpuemu_21.cpp: gen/cpuemu_0.cpp

gen/cpuemu_22.cpp: gen/cpuemu_0.cpp

gen/cpuemu_31.cpp: gen/cpuemu_0.cpp

gen/cpuemu_32.cpp: gen/cpuemu_0.cpp

gen/cpuemu_33.cpp: gen/cpuemu_0.cpp

gen/cpustbl.cpp: gen/cpuemu_0.cpp

gen/cputbl.h: gen/cpuemu_0.cpp

gen/linetoscr.cpp: gen/genlinetoscr
	gen/genlinetoscr > gen/linetoscr.cpp

fs_uae_device_helper_objects = \
obj/fs_uae_device_helper_libfsemu_src_base.o \
obj/fs_uae_device_helper_libfsemu_src_filesys.o \
obj/fs_uae_device_helper_libfsemu_src_hashtable.o \
obj/fs_uae_device_helper_libfsemu_src_list.o \
obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_linux_evdev.o \
obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_macosx_hidmanager.o \
obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_macosx_hidutilities.o \
obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_manymouse.o \
obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_windows_wminput.o \
obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_x11_xinput2.o \
obj/fs_uae_device_helper_libfsemu_src_ml_util.o \
obj/fs_uae_device_helper_libfsemu_src_string.o \
obj/fs_uae_device_helper_src_fs-uae_device-helper.o

fs_uae_objects = \
obj/fs_uae_gen_blitfunc.o \
obj/fs_uae_gen_blittable.o \
obj/fs_uae_gen_compemu.o \
obj/fs_uae_gen_compstbl.o \
obj/fs_uae_gen_cpudefs.o \
obj/fs_uae_gen_cpuemu_0.o \
obj/fs_uae_gen_cpuemu_11.o \
obj/fs_uae_gen_cpuemu_13.o \
obj/fs_uae_gen_cpuemu_20.o \
obj/fs_uae_gen_cpuemu_21.o \
obj/fs_uae_gen_cpuemu_22.o \
obj/fs_uae_gen_cpuemu_31.o \
obj/fs_uae_gen_cpuemu_32.o \
obj/fs_uae_gen_cpuemu_33.o \
obj/fs_uae_gen_cpustbl.o \
obj/fs_uae_libfsemu_src_base.o \
obj/fs_uae_libfsemu_src_config.o \
obj/fs_uae_libfsemu_src_emu_actions.o \
obj/fs_uae_libfsemu_src_emu_audio_common.o \
obj/fs_uae_libfsemu_src_emu_audio_debug.o \
obj/fs_uae_libfsemu_src_emu_audio_dummy.o \
obj/fs_uae_libfsemu_src_emu_audio_dummy.o \
obj/fs_uae_libfsemu_src_emu_audio_openal.o \
obj/fs_uae_libfsemu_src_emu_audio_sdl.o \
obj/fs_uae_libfsemu_src_emu_dialog.o \
obj/fs_uae_libfsemu_src_emu_emu.o \
obj/fs_uae_libfsemu_src_emu_emu_lua.o \
obj/fs_uae_libfsemu_src_emu_font.o \
obj/fs_uae_libfsemu_src_emu_hud.o \
obj/fs_uae_libfsemu_src_emu_input.o \
obj/fs_uae_libfsemu_src_emu_menu.o \
obj/fs_uae_libfsemu_src_emu_netplay.o \
obj/fs_uae_libfsemu_src_emu_render.o \
obj/fs_uae_libfsemu_src_emu_scanlines.o \
obj/fs_uae_libfsemu_src_emu_texture.o \
obj/fs_uae_libfsemu_src_emu_theme.o \
obj/fs_uae_libfsemu_src_emu_util.o \
obj/fs_uae_libfsemu_src_emu_video.o \
obj/fs_uae_libfsemu_src_emu_video_buffer.o \
obj/fs_uae_libfsemu_src_emu_video_options.o \
obj/fs_uae_libfsemu_src_emu_xml_shader.o \
obj/fs_uae_libfsemu_src_eventlog.o \
obj/fs_uae_libfsemu_src_filesys.o \
obj/fs_uae_libfsemu_src_glee.o \
obj/fs_uae_libfsemu_src_hashtable.o \
obj/fs_uae_libfsemu_src_image.o \
obj/fs_uae_libfsemu_src_inifile.o \
obj/fs_uae_libfsemu_src_init.o \
obj/fs_uae_libfsemu_src_list.o \
obj/fs_uae_libfsemu_src_log.o \
obj/fs_uae_libfsemu_src_lua_lapi.o \
obj/fs_uae_libfsemu_src_lua_lauxlib.o \
obj/fs_uae_libfsemu_src_lua_lbaselib.o \
obj/fs_uae_libfsemu_src_lua_lbitlib.o \
obj/fs_uae_libfsemu_src_lua_lcode.o \
obj/fs_uae_libfsemu_src_lua_lcorolib.o \
obj/fs_uae_libfsemu_src_lua_lctype.o \
obj/fs_uae_libfsemu_src_lua_ldblib.o \
obj/fs_uae_libfsemu_src_lua_ldebug.o \
obj/fs_uae_libfsemu_src_lua_ldo.o \
obj/fs_uae_libfsemu_src_lua_ldump.o \
obj/fs_uae_libfsemu_src_lua_lfunc.o \
obj/fs_uae_libfsemu_src_lua_lgc.o \
obj/fs_uae_libfsemu_src_lua_linit.o \
obj/fs_uae_libfsemu_src_lua_liolib.o \
obj/fs_uae_libfsemu_src_lua_llex.o \
obj/fs_uae_libfsemu_src_lua_lmathlib.o \
obj/fs_uae_libfsemu_src_lua_lmem.o \
obj/fs_uae_libfsemu_src_lua_loadlib.o \
obj/fs_uae_libfsemu_src_lua_lobject.o \
obj/fs_uae_libfsemu_src_lua_lopcodes.o \
obj/fs_uae_libfsemu_src_lua_loslib.o \
obj/fs_uae_libfsemu_src_lua_lparser.o \
obj/fs_uae_libfsemu_src_lua_lstate.o \
obj/fs_uae_libfsemu_src_lua_lstring.o \
obj/fs_uae_libfsemu_src_lua_lstrlib.o \
obj/fs_uae_libfsemu_src_lua_ltable.o \
obj/fs_uae_libfsemu_src_lua_ltablib.o \
obj/fs_uae_libfsemu_src_lua_ltm.o \
obj/fs_uae_libfsemu_src_lua_lundump.o \
obj/fs_uae_libfsemu_src_lua_lvm.o \
obj/fs_uae_libfsemu_src_lua_lzio.o \
obj/fs_uae_libfsemu_src_ml_clock.o \
obj/fs_uae_libfsemu_src_ml_config.o \
obj/fs_uae_libfsemu_src_ml_input.o \
obj/fs_uae_libfsemu_src_ml_keyboard.o \
obj/fs_uae_libfsemu_src_ml_macosx.o \
obj/fs_uae_libfsemu_src_ml_manymouse_linux_evdev.o \
obj/fs_uae_libfsemu_src_ml_manymouse_macosx_hidmanager.o \
obj/fs_uae_libfsemu_src_ml_manymouse_macosx_hidutilities.o \
obj/fs_uae_libfsemu_src_ml_manymouse_manymouse.o \
obj/fs_uae_libfsemu_src_ml_manymouse_windows_wminput.o \
obj/fs_uae_libfsemu_src_ml_manymouse_x11_xinput2.o \
obj/fs_uae_libfsemu_src_ml_ml.o \
obj/fs_uae_libfsemu_src_ml_mouse.o \
obj/fs_uae_libfsemu_src_ml_opengl.o \
obj/fs_uae_libfsemu_src_ml_rawinput.o \
obj/fs_uae_libfsemu_src_ml_render.o \
obj/fs_uae_libfsemu_src_ml_sdl.o \
obj/fs_uae_libfsemu_src_ml_util.o \
obj/fs_uae_libfsemu_src_ml_video.o \
obj/fs_uae_libfsemu_src_ml_video.o \
obj/fs_uae_libfsemu_src_ml_video_mode.o \
obj/fs_uae_libfsemu_src_ml_video_sync.o \
obj/fs_uae_libfsemu_src_ml_windows.o \
obj/fs_uae_libfsemu_src_ml_x11.o \
obj/fs_uae_libfsemu_src_opengl.o \
obj/fs_uae_libfsemu_src_queue.o \
obj/fs_uae_libfsemu_src_random.o \
obj/fs_uae_libfsemu_src_ref.o \
obj/fs_uae_libfsemu_src_string.o \
obj/fs_uae_libfsemu_src_thread.o \
obj/fs_uae_libfsemu_src_time.o \
obj/fs_uae_libfsemu_src_unicode.o \
obj/fs_uae_src_a2091.o \
obj/fs_uae_src_akiko.o \
obj/fs_uae_src_amax.o \
obj/fs_uae_src_ar.o \
obj/fs_uae_src_arcadia.o \
obj/fs_uae_src_archivers_dms_crc_csum.o \
obj/fs_uae_src_archivers_dms_getbits.o \
obj/fs_uae_src_archivers_dms_maketbl.o \
obj/fs_uae_src_archivers_dms_pfile.o \
obj/fs_uae_src_archivers_dms_tables.o \
obj/fs_uae_src_archivers_dms_u_deep.o \
obj/fs_uae_src_archivers_dms_u_heavy.o \
obj/fs_uae_src_archivers_dms_u_init.o \
obj/fs_uae_src_archivers_dms_u_medium.o \
obj/fs_uae_src_archivers_dms_u_quick.o \
obj/fs_uae_src_archivers_dms_u_rle.o \
obj/fs_uae_src_archivers_zip_unzip.o \
obj/fs_uae_src_aros.rom.o \
obj/fs_uae_src_audio.o \
obj/fs_uae_src_autoconf.o \
obj/fs_uae_src_blitter.o \
obj/fs_uae_src_blkdev.o \
obj/fs_uae_src_blkdev_cdimage.o \
obj/fs_uae_src_bsdsocket.o \
obj/fs_uae_src_calc.o \
obj/fs_uae_src_cd32_fmv.o \
obj/fs_uae_src_cdrom.o \
obj/fs_uae_src_cdtv.o \
obj/fs_uae_src_cfgfile.o \
obj/fs_uae_src_cia.o \
obj/fs_uae_src_consolehook.o \
obj/fs_uae_src_cpummu.o \
obj/fs_uae_src_cpummu30.o \
obj/fs_uae_src_crc32.o \
obj/fs_uae_src_custom.o \
obj/fs_uae_src_debug.o \
obj/fs_uae_src_disk.o \
obj/fs_uae_src_diskutil.o \
obj/fs_uae_src_dongle.o \
obj/fs_uae_src_drawing.o \
obj/fs_uae_src_driveclick.o \
obj/fs_uae_src_enforcer.o \
obj/fs_uae_src_events.o \
obj/fs_uae_src_expansion.o \
obj/fs_uae_src_fdi2raw.o \
obj/fs_uae_src_filesys.o \
obj/fs_uae_src_fpp.o \
obj/fs_uae_src_fs-uae_config.o \
obj/fs_uae_src_fs-uae_input.o \
obj/fs_uae_src_fs-uae_joystick.o \
obj/fs_uae_src_fs-uae_keyboard.o \
obj/fs_uae_src_fs-uae_luascript.o \
obj/fs_uae_src_fs-uae_main.o \
obj/fs_uae_src_fs-uae_menu.o \
obj/fs_uae_src_fs-uae_mouse.o \
obj/fs_uae_src_fs-uae_paths.o \
obj/fs_uae_src_fs-uae_recording.o \
obj/fs_uae_src_fs-uae_uae_config.o \
obj/fs_uae_src_fs-uae_video.o \
obj/fs_uae_src_fsdb.o \
obj/fs_uae_src_fsusage.o \
obj/fs_uae_src_gayle.o \
obj/fs_uae_src_gfxboard.o \
obj/fs_uae_src_gfxutil.o \
obj/fs_uae_src_hardfile.o \
obj/fs_uae_src_hrtmon.rom.o \
obj/fs_uae_src_identify.o \
obj/fs_uae_src_inputdevice.o \
obj/fs_uae_src_inputrecord.o \
obj/fs_uae_src_isofs.o \
obj/fs_uae_src_jit_compemu_fpp.o \
obj/fs_uae_src_jit_compemu_support.o \
obj/fs_uae_src_keybuf.o \
obj/fs_uae_src_luascript.o \
obj/fs_uae_src_main.o \
obj/fs_uae_src_memory.o \
obj/fs_uae_src_missing.o \
obj/fs_uae_src_native2amiga.o \
obj/fs_uae_src_ncr_scsi.o \
obj/fs_uae_src_newcpu.o \
obj/fs_uae_src_newcpu_common.o \
obj/fs_uae_src_od-fs_ahi_v2.o \
obj/fs_uae_src_od-fs_ahi_winuae.o \
obj/fs_uae_src_od-fs_audio.o \
obj/fs_uae_src_od-fs_blkdev-linux.o \
obj/fs_uae_src_od-fs_bsdsocket_host.o \
obj/fs_uae_src_od-fs_caps.o \
obj/fs_uae_src_od-fs_cda_play.o \
obj/fs_uae_src_od-fs_cdimage_stubs.o \
obj/fs_uae_src_od-fs_charset.o \
obj/fs_uae_src_od-fs_clipboard.o \
obj/fs_uae_src_od-fs_clock.o \
obj/fs_uae_src_od-fs_driveclick.o \
obj/fs_uae_src_od-fs_filesys_host.o \
obj/fs_uae_src_od-fs_fsdb_host.o \
obj/fs_uae_src_od-fs_gui.o \
obj/fs_uae_src_od-fs_hardfile_host.o \
obj/fs_uae_src_od-fs_input.o \
obj/fs_uae_src_od-fs_keymap.o \
obj/fs_uae_src_od-fs_libamiga.o \
obj/fs_uae_src_od-fs_logging.o \
obj/fs_uae_src_od-fs_mman.o \
obj/fs_uae_src_od-fs_parser.o \
obj/fs_uae_src_od-fs_paths.o \
obj/fs_uae_src_od-fs_picasso96.o \
obj/fs_uae_src_od-fs_random.o \
obj/fs_uae_src_od-fs_roms.o \
obj/fs_uae_src_od-fs_serial_host.o \
obj/fs_uae_src_od-fs_stubs.o \
obj/fs_uae_src_od-fs_support.o \
obj/fs_uae_src_od-fs_threading.o \
obj/fs_uae_src_od-fs_uae_host.o \
obj/fs_uae_src_od-fs_uaemisc.o \
obj/fs_uae_src_od-fs_util.o \
obj/fs_uae_src_od-fs_version.o \
obj/fs_uae_src_od-fs_video.o \
obj/fs_uae_src_qemuvga_cirrus_vga.o \
obj/fs_uae_src_qemuvga_lsi53c895a.o \
obj/fs_uae_src_qemuvga_qemuuaeglue.o \
obj/fs_uae_src_qemuvga_vga.o \
obj/fs_uae_src_readcpu.o \
obj/fs_uae_src_rommgr.o \
obj/fs_uae_src_savestate.o \
obj/fs_uae_src_scp.o \
obj/fs_uae_src_scsi.o \
obj/fs_uae_src_scsiemul.o \
obj/fs_uae_src_scsitape.o \
obj/fs_uae_src_specialmonitors.o \
obj/fs_uae_src_statusline.o \
obj/fs_uae_src_traps.o \
obj/fs_uae_src_uaeexe.o \
obj/fs_uae_src_uaelib.o \
obj/fs_uae_src_uaenative.o \
obj/fs_uae_src_uaeresource.o \
obj/fs_uae_src_uaeserial.o \
obj/fs_uae_src_zfile.o \
obj/fs_uae_src_zfile_archive.o

gen_build68k_objects = \
obj/gen_build68k_src_build68k.o \
obj/gen_build68k_src_writelog.o

gen_genblitter_objects = \
obj/gen_genblitter_src_blitops.o \
obj/gen_genblitter_src_genblitter.o \
obj/gen_genblitter_src_writelog.o

gen_gencomp_objects = \
obj/gen_gencomp_gen_cpudefs.o \
obj/gen_gencomp_src_jit_gencomp.o \
obj/gen_gencomp_src_missing.o \
obj/gen_gencomp_src_readcpu.o

gen_gencpu_objects = \
obj/gen_gencpu_gen_cpudefs.o \
obj/gen_gencpu_src_gencpu.o \
obj/gen_gencpu_src_missing.o \
obj/gen_gencpu_src_readcpu.o

gen_genlinetoscr_objects = \
obj/gen_genlinetoscr_src_genlinetoscr.o

fs-uae: $(fs_uae_objects)
	mkdir -p `dirname $@`
	rm -f fs-uae
	$(CXX) $(fs_uae_objects)  $(AM_LDFLAGS) $(LDFLAGS) $(AM_LIBS) $(LIBS) -o $@

fs-uae-device-helper: $(fs_uae_device_helper_objects)
	mkdir -p `dirname $@`
	rm -f fs-uae-device-helper
	$(CC) $(fs_uae_device_helper_objects)  $(AM_LDFLAGS) $(LDFLAGS) $(AM_LIBS) $(LIBS) -o $@

gen/build68k: $(gen_build68k_objects)
	mkdir -p `dirname $@`
	rm -f gen/build68k
	$(CXX) $(gen_build68k_objects)  $(AM_LDFLAGS) $(LDFLAGS) $(AM_LIBS) $(LIBS) -o $@

gen/genblitter: $(gen_genblitter_objects)
	mkdir -p `dirname $@`
	rm -f gen/genblitter
	$(CXX) $(gen_genblitter_objects)  $(AM_LDFLAGS) $(LDFLAGS) $(AM_LIBS) $(LIBS) -o $@

gen/gencomp: $(gen_gencomp_objects)
	mkdir -p `dirname $@`
	rm -f gen/gencomp
	$(CXX) $(gen_gencomp_objects)  $(AM_LDFLAGS) $(LDFLAGS) $(AM_LIBS) $(LIBS) -o $@

gen/gencpu: $(gen_gencpu_objects)
	mkdir -p `dirname $@`
	rm -f gen/gencpu
	$(CXX) $(gen_gencpu_objects)  $(AM_LDFLAGS) $(LDFLAGS) $(AM_LIBS) $(LIBS) -o $@

gen/genlinetoscr: $(gen_genlinetoscr_objects)
	mkdir -p `dirname $@`
	rm -f gen/genlinetoscr
	$(CXX) $(gen_genlinetoscr_objects)  $(AM_LDFLAGS) $(LDFLAGS) $(AM_LIBS) $(LIBS) -o $@

obj/fs_uae_device_helper_libfsemu_src_base.o: libfsemu/src/base.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_filesys.o: libfsemu/src/filesys.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_hashtable.o: libfsemu/src/hashtable.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_list.o: libfsemu/src/list.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_linux_evdev.o: libfsemu/src/ml/manymouse/linux_evdev.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_macosx_hidmanager.o: libfsemu/src/ml/manymouse/macosx_hidmanager.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_macosx_hidutilities.o: libfsemu/src/ml/manymouse/macosx_hidutilities.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_manymouse.o: libfsemu/src/ml/manymouse/manymouse.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_windows_wminput.o: libfsemu/src/ml/manymouse/windows_wminput.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_ml_manymouse_x11_xinput2.o: libfsemu/src/ml/manymouse/x11_xinput2.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_ml_util.o: libfsemu/src/ml/util.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_libfsemu_src_string.o: libfsemu/src/string.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_device_helper_src_fs-uae_device-helper.o: src/fs-uae/device-helper.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_gen_blitfunc.o: gen/blitfunc.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_gen_blittable.o: gen/blittable.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_gen_compemu.o: gen/compemu.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_gen_compstbl.o: gen/compstbl.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_gen_cpudefs.o: gen/cpudefs.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_gen_cpuemu_0.o: gen/cpuemu_0.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -O0 -c $< -o $@

obj/fs_uae_gen_cpuemu_11.o: gen/cpuemu_11.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -O0 -c $< -o $@

obj/fs_uae_gen_cpuemu_13.o: gen/cpuemu_13.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -O0 -c $< -o $@

obj/fs_uae_gen_cpuemu_20.o: gen/cpuemu_20.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -O0 -c $< -o $@

obj/fs_uae_gen_cpuemu_21.o: gen/cpuemu_21.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -O0 -c $< -o $@

obj/fs_uae_gen_cpuemu_22.o: gen/cpuemu_22.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -O0 -c $< -o $@

obj/fs_uae_gen_cpuemu_31.o: gen/cpuemu_31.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -O0 -c $< -o $@

obj/fs_uae_gen_cpuemu_32.o: gen/cpuemu_32.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -O0 -c $< -o $@

obj/fs_uae_gen_cpuemu_33.o: gen/cpuemu_33.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -O0 -c $< -o $@

obj/fs_uae_gen_cpustbl.o: gen/cpustbl.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_base.o: libfsemu/src/base.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_config.o: libfsemu/src/config.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_actions.o: libfsemu/src/emu/actions.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_audio_common.o: libfsemu/src/emu/audio_common.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_audio_debug.o: libfsemu/src/emu/audio_debug.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_audio_dummy.o: libfsemu/src/emu/audio_dummy.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_audio_openal.o: libfsemu/src/emu/audio_openal.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_audio_sdl.o: libfsemu/src/emu/audio_sdl.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_dialog.o: libfsemu/src/emu/dialog.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_emu.o: libfsemu/src/emu/emu.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_emu_lua.o: libfsemu/src/emu/emu_lua.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_font.o: libfsemu/src/emu/font.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_hud.o: libfsemu/src/emu/hud.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_input.o: libfsemu/src/emu/input.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_menu.o: libfsemu/src/emu/menu.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_netplay.o: libfsemu/src/emu/netplay.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_render.o: libfsemu/src/emu/render.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_scanlines.o: libfsemu/src/emu/scanlines.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_texture.o: libfsemu/src/emu/texture.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_theme.o: libfsemu/src/emu/theme.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_util.o: libfsemu/src/emu/util.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_video.o: libfsemu/src/emu/video.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_video_buffer.o: libfsemu/src/emu/video_buffer.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_video_options.o: libfsemu/src/emu/video_options.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_emu_xml_shader.o: libfsemu/src/emu/xml_shader.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_eventlog.o: libfsemu/src/eventlog.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_filesys.o: libfsemu/src/filesys.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_glee.o: libfsemu/src/glee.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_hashtable.o: libfsemu/src/hashtable.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_image.o: libfsemu/src/image.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_inifile.o: libfsemu/src/inifile.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_init.o: libfsemu/src/init.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_list.o: libfsemu/src/list.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_log.o: libfsemu/src/log.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lapi.o: libfsemu/src/lua/lapi.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lauxlib.o: libfsemu/src/lua/lauxlib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lbaselib.o: libfsemu/src/lua/lbaselib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lbitlib.o: libfsemu/src/lua/lbitlib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lcode.o: libfsemu/src/lua/lcode.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lcorolib.o: libfsemu/src/lua/lcorolib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lctype.o: libfsemu/src/lua/lctype.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_ldblib.o: libfsemu/src/lua/ldblib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_ldebug.o: libfsemu/src/lua/ldebug.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_ldo.o: libfsemu/src/lua/ldo.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_ldump.o: libfsemu/src/lua/ldump.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lfunc.o: libfsemu/src/lua/lfunc.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lgc.o: libfsemu/src/lua/lgc.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_linit.o: libfsemu/src/lua/linit.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_liolib.o: libfsemu/src/lua/liolib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_llex.o: libfsemu/src/lua/llex.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lmathlib.o: libfsemu/src/lua/lmathlib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lmem.o: libfsemu/src/lua/lmem.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_loadlib.o: libfsemu/src/lua/loadlib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lobject.o: libfsemu/src/lua/lobject.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lopcodes.o: libfsemu/src/lua/lopcodes.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_loslib.o: libfsemu/src/lua/loslib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lparser.o: libfsemu/src/lua/lparser.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lstate.o: libfsemu/src/lua/lstate.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lstring.o: libfsemu/src/lua/lstring.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lstrlib.o: libfsemu/src/lua/lstrlib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_ltable.o: libfsemu/src/lua/ltable.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_ltablib.o: libfsemu/src/lua/ltablib.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_ltm.o: libfsemu/src/lua/ltm.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lundump.o: libfsemu/src/lua/lundump.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lvm.o: libfsemu/src/lua/lvm.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_lua_lzio.o: libfsemu/src/lua/lzio.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_clock.o: libfsemu/src/ml/clock.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_config.o: libfsemu/src/ml/config.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_input.o: libfsemu/src/ml/input.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_keyboard.o: libfsemu/src/ml/keyboard.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_macosx.o: libfsemu/src/ml/macosx.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_manymouse_linux_evdev.o: libfsemu/src/ml/manymouse/linux_evdev.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_manymouse_macosx_hidmanager.o: libfsemu/src/ml/manymouse/macosx_hidmanager.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_manymouse_macosx_hidutilities.o: libfsemu/src/ml/manymouse/macosx_hidutilities.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_manymouse_manymouse.o: libfsemu/src/ml/manymouse/manymouse.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_manymouse_windows_wminput.o: libfsemu/src/ml/manymouse/windows_wminput.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_manymouse_x11_xinput2.o: libfsemu/src/ml/manymouse/x11_xinput2.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_ml.o: libfsemu/src/ml/ml.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_mouse.o: libfsemu/src/ml/mouse.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_opengl.o: libfsemu/src/ml/opengl.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_rawinput.o: libfsemu/src/ml/rawinput.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_render.o: libfsemu/src/ml/render.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_sdl.o: libfsemu/src/ml/sdl.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_util.o: libfsemu/src/ml/util.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_video.o: libfsemu/src/ml/video.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_video_mode.o: libfsemu/src/ml/video_mode.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_video_sync.o: libfsemu/src/ml/video_sync.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_windows.o: libfsemu/src/ml/windows.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ml_x11.o: libfsemu/src/ml/x11.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_opengl.o: libfsemu/src/opengl.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_queue.o: libfsemu/src/queue.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_random.o: libfsemu/src/random.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_ref.o: libfsemu/src/ref.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_string.o: libfsemu/src/string.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_thread.o: libfsemu/src/thread.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_time.o: libfsemu/src/time.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_libfsemu_src_unicode.o: libfsemu/src/unicode.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_a2091.o: src/a2091.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_akiko.o: src/akiko.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_amax.o: src/amax.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_ar.o: src/ar.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_arcadia.o: src/arcadia.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_crc_csum.o: src/archivers/dms/crc_csum.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_getbits.o: src/archivers/dms/getbits.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_maketbl.o: src/archivers/dms/maketbl.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_pfile.o: src/archivers/dms/pfile.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_tables.o: src/archivers/dms/tables.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_u_deep.o: src/archivers/dms/u_deep.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_u_heavy.o: src/archivers/dms/u_heavy.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_u_init.o: src/archivers/dms/u_init.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_u_medium.o: src/archivers/dms/u_medium.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_u_quick.o: src/archivers/dms/u_quick.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_dms_u_rle.o: src/archivers/dms/u_rle.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_archivers_zip_unzip.o: src/archivers/zip/unzip.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_aros.rom.o: src/aros.rom.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_audio.o: src/audio.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_autoconf.o: src/autoconf.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_blitter.o: src/blitter.cpp gen/blit.h
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_blkdev.o: src/blkdev.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_blkdev_cdimage.o: src/blkdev_cdimage.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_bsdsocket.o: src/bsdsocket.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_calc.o: src/calc.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_cd32_fmv.o: src/cd32_fmv.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_cdrom.o: src/cdrom.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_cdtv.o: src/cdtv.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_cfgfile.o: src/cfgfile.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_cia.o: src/cia.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_consolehook.o: src/consolehook.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_cpummu.o: src/cpummu.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_cpummu30.o: src/cpummu30.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_crc32.o: src/crc32.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_custom.o: src/custom.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_debug.o: src/debug.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_disk.o: src/disk.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_diskutil.o: src/diskutil.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_dongle.o: src/dongle.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_drawing.o: src/drawing.cpp gen/linetoscr.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_driveclick.o: src/driveclick.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_enforcer.o: src/enforcer.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_events.o: src/events.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_expansion.o: src/expansion.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fdi2raw.o: src/fdi2raw.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_filesys.o: src/filesys.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fpp.o: src/fpp.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_config.o: src/fs-uae/config.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_input.o: src/fs-uae/input.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_joystick.o: src/fs-uae/joystick.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_keyboard.o: src/fs-uae/keyboard.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_luascript.o: src/fs-uae/luascript.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_main.o: src/fs-uae/main.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_menu.o: src/fs-uae/menu.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_mouse.o: src/fs-uae/mouse.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_paths.o: src/fs-uae/paths.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_recording.o: src/fs-uae/recording.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_uae_config.o: src/fs-uae/uae_config.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fs-uae_video.o: src/fs-uae/video.c
	mkdir -p `dirname $@`
	$(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fsdb.o: src/fsdb.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_fsusage.o: src/fsusage.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_gayle.o: src/gayle.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_gfxboard.o: src/gfxboard.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_gfxutil.o: src/gfxutil.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_hardfile.o: src/hardfile.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_hrtmon.rom.o: src/hrtmon.rom.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_identify.o: src/identify.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_inputdevice.o: src/inputdevice.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_inputrecord.o: src/inputrecord.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_isofs.o: src/isofs.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_jit_compemu_fpp.o: src/jit/compemu_fpp.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_jit_compemu_support.o: src/jit/compemu_support.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_keybuf.o: src/keybuf.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_luascript.o: src/luascript.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_main.o: src/main.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_memory.o: src/memory.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_missing.o: src/missing.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_native2amiga.o: src/native2amiga.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_ncr_scsi.o: src/ncr_scsi.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_newcpu.o: src/newcpu.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_newcpu_common.o: src/newcpu_common.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_ahi_v2.o: src/od-fs/ahi_v2.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_ahi_winuae.o: src/od-fs/ahi_winuae.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_audio.o: src/od-fs/audio.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_blkdev-linux.o: src/od-fs/blkdev-linux.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_bsdsocket_host.o: src/od-fs/bsdsocket_host.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_caps.o: src/od-fs/caps.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_cda_play.o: src/od-fs/cda_play.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_cdimage_stubs.o: src/od-fs/cdimage_stubs.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_charset.o: src/od-fs/charset.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_clipboard.o: src/od-fs/clipboard.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_clock.o: src/od-fs/clock.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_driveclick.o: src/od-fs/driveclick.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_filesys_host.o: src/od-fs/filesys_host.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_fsdb_host.o: src/od-fs/fsdb_host.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_gui.o: src/od-fs/gui.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_hardfile_host.o: src/od-fs/hardfile_host.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_input.o: src/od-fs/input.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_keymap.o: src/od-fs/keymap.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_libamiga.o: src/od-fs/libamiga.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_logging.o: src/od-fs/logging.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_mman.o: src/od-fs/mman.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_parser.o: src/od-fs/parser.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_paths.o: src/od-fs/paths.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_picasso96.o: src/od-fs/picasso96.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_random.o: src/od-fs/random.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_roms.o: src/od-fs/roms.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_serial_host.o: src/od-fs/serial_host.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_stubs.o: src/od-fs/stubs.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_support.o: src/od-fs/support.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_threading.o: src/od-fs/threading.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_uae_host.o: src/od-fs/uae_host.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_uaemisc.o: src/od-fs/uaemisc.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_util.o: src/od-fs/util.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_version.o: src/od-fs/version.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_od-fs_video.o: src/od-fs/video.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_qemuvga_cirrus_vga.o: src/qemuvga/cirrus_vga.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_qemuvga_lsi53c895a.o: src/qemuvga/lsi53c895a.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_qemuvga_qemuuaeglue.o: src/qemuvga/qemuuaeglue.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_qemuvga_vga.o: src/qemuvga/vga.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_readcpu.o: src/readcpu.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_rommgr.o: src/rommgr.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_savestate.o: src/savestate.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_scp.o: src/scp.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_scsi.o: src/scsi.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_scsiemul.o: src/scsiemul.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_scsitape.o: src/scsitape.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_specialmonitors.o: src/specialmonitors.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_statusline.o: src/statusline.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_traps.o: src/traps.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_uaeexe.o: src/uaeexe.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_uaelib.o: src/uaelib.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_uaenative.o: src/uaenative.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_uaeresource.o: src/uaeresource.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_uaeserial.o: src/uaeserial.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_zfile.o: src/zfile.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/fs_uae_src_zfile_archive.o: src/zfile_archive.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_build68k_src_build68k.o: src/build68k.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_build68k_src_writelog.o: src/writelog.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_genblitter_src_blitops.o: src/blitops.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_genblitter_src_genblitter.o: src/genblitter.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_genblitter_src_writelog.o: src/writelog.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_gencomp_gen_cpudefs.o: gen/cpudefs.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_gencomp_src_jit_gencomp.o: src/jit/gencomp.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_gencomp_src_missing.o: src/missing.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_gencomp_src_readcpu.o: src/readcpu.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_gencpu_gen_cpudefs.o: gen/cpudefs.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_gencpu_src_gencpu.o: src/gencpu.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_gencpu_src_missing.o: src/missing.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_gencpu_src_readcpu.o: src/readcpu.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@

obj/gen_genlinetoscr_src_genlinetoscr.o: src/genlinetoscr.cpp
	mkdir -p `dirname $@`
	$(CXX) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_CPPFLAGS) $(CPPFLAGS) -c $< -o $@


version := $(strip $(shell cat VERSION))
series := $(strip $(shell cat SERIES))

ifeq ($(wildcard libfsemu),)
	libfsemu_dir := "../libfsemu"
else
	libfsemu_dir := "libfsemu"
endif

build_dir := "."
dist_name = fs-uae-$(version)
dist_dir := $(build_dir)/$(dist_name)
# dist_file := $(build_dir)/$(dist_name).tar.gz

distdir-base:
	rm -Rf $(dist_dir)/*
	mkdir -p $(dist_dir)
	# cp -a $(dist_dir_launcher) $(dist_dir)/launcher

	mkdir -p $(dist_dir)/obj
	touch $(dist_dir)/obj/.dummy
	mkdir -p $(dist_dir)/out
	touch $(dist_dir)/out/.dummy
	cp -a INSTALL README COPYING NEWS AUTHORS $(dist_dir)
	cp -a VERSION SERIES ChangeLog $(dist_dir)
	# windows.mk macosx.mk debian.mk
	cp -a fs-uae.spec $(dist_dir)
	cp -a example.conf $(dist_dir)
	cp -a configure.ac $(dist_dir)
	cp -a bootstrap.sh $(dist_dir)
	cp -a Makefile.py $(dist_dir)
	cp -a src contrib share licenses $(dist_dir)
	rm -Rf $(dist_dir)/src/od-win32
	rm -Rf $(dist_dir)/src/prowizard
	rm -Rf $(dist_dir)/src/archivers/lha
	rm -Rf $(dist_dir)/src/archivers/lzx
	rm -Rf $(dist_dir)/src/archivers/xfd
	rm -Rf $(dist_dir)/src/jit2
	rm -f $(dist_dir)/src/akiko2.cpp
	rm -f $(dist_dir)/src/custom2.cpp
	rm -f $(dist_dir)/src/core.cw4.cpp
	rm -f $(dist_dir)/src/catweasel.cpp

	find $(dist_dir)/share -name "*.mo" -delete
	# mkdir -p $(dist_dir)/gensrc
	# cp -a gensrc/*.cpp gensrc/*.h $(dist_dir)/gensrc

	mkdir -p $(dist_dir)/libfsemu
	cp -a $(libfsemu_dir)/COPYING $(dist_dir)/libfsemu
	cp -a $(libfsemu_dir)/README $(dist_dir)/libfsemu
	cp -a $(libfsemu_dir)/include $(dist_dir)/libfsemu
	cp -a $(libfsemu_dir)/src $(dist_dir)/libfsemu

	mkdir -p $(dist_dir)/po
	cp -a po/*.po $(dist_dir)/po/
	cp -a po/update.py $(dist_dir)/po/update.py
	cp -a po/update.sh $(dist_dir)/po/update.sh

	mkdir -p $(dist_dir)/doc
	cp -a doc/Default.fs-uae $(dist_dir)/doc/

	mkdir -p $(dist_dir)/macosx
	cp -a macosx/Makefile $(dist_dir)/macosx/
	cp -a macosx/fs-make-standalone-app.py $(dist_dir)/macosx/
	cp -a macosx/template $(dist_dir)/macosx/

	mkdir -p $(dist_dir)/windows
	cp -a windows/Makefile $(dist_dir)/windows/
	# cp -a windows/launcher-proxy.exe $(dist_dir)/windows/
	# cp -a windows/game-center-proxy.exe $(dist_dir)/windows/
	cp -a windows/replace_icon.py $(dist_dir)/windows/
	cp -a windows/fs-uae.iss $(dist_dir)/windows/
	# cp -a windows/launcher.iss $(dist_dir)/windows/
	# cp -a windows/game-center.iss $(dist_dir)/windows/

	mkdir -p $(dist_dir)/debian
	cp -a debian/changelog $(dist_dir)/debian/
	cp -a debian/compat $(dist_dir)/debian/
	cp -a debian/control $(dist_dir)/debian/
	cp -a debian/copyright $(dist_dir)/debian/
	cp -a debian/rules $(dist_dir)/debian/
	cp -a debian/source $(dist_dir)/debian/

	mkdir -p $(dist_dir)/util
	#cp -a util/fix_64_bit.py $(dist_dir)/util/
	#cd $(dist_dir) && python util/fix_64_bit.py
	cp -a util/update-version.py $(dist_dir)/util/

	mkdir -p $(dist_dir)/icon
	cp icon/fs-uae.ico $(dist_dir)/icon/
	cp icon/fs-uae.icns $(dist_dir)/icon/
	cp icon/fs-uae-launcher.ico $(dist_dir)/icon/
	cp icon/fs-uae-launcher.icns $(dist_dir)/icon/
	cp icon/fs-uae-config.icns $(dist_dir)/icon/

	find $(dist_dir) -name "*~" -delete

distdir: distdir-base
	cd $(dist_dir) && ./bootstrap.sh
	cd $(dist_dir) && rm -Rf autom4te.cache
	cd $(dist_dir) && python util/update-version.py

distcheck: distdir
	cd $(dist_dir) && ./configure
	cd $(dist_dir) && $(make)

po-dist:
	mkdir -p dist/$(series)/po/fs-uae
	cp po/*.po dist/$(series)/po/fs-uae/

	# mkdir -p dist/$(series)/po/fs-uae-launcher
	# cp launcher/po/*.po dist/$(series)/po/fs-uae-launcher/

#dist: distdir pubfiles-source po-dist
dist: distdir po-dist
	# find $(dist_dir_launcher) -exec touch \{\} \;
	find $(dist_dir) -exec touch \{\} \;

	# tar zcfv fs-uae-launcher-$(version).tar.gz $(dist_dir_launcher)
	cd "$(build_dir)" && tar zcfv $(dist_name).tar.gz $(dist_name)
	# mkdir -p dist/$(series)/$(version)
	# mv fs-uae-$(version).tar.gz dist/$(series)/$(version)/
	# mv fs-uae-launcher-$(version).tar.gz dist/$(series)/$(version)/
	# mkdir -p dist/files/
	# cp doc/Default.fs-uae dist/files/
	# cp server/fs_uae_netplay_server/game.py	 # 	dist/files/fs-uae-netplay-server.py
	# cp server/fs_uae_netplay_server/game.py	 # 	dist/$(series)/$(version)/fs-uae-game-server-$(version).py

install:
	install -d $(DESTDIR)$(prefix)/bin
	install fs-uae $(DESTDIR)$(prefix)/bin/fs-uae
	install fs-uae-device-helper $(DESTDIR)$(prefix)/bin/fs-uae-device-helper
	install -d $(DESTDIR)$(prefix)/share
	cp -R share/* $(DESTDIR)$(prefix)/share

	install -d $(DESTDIR)$(docdir)
	cp README COPYING example.conf $(DESTDIR)$(docdir)

debsrc: dist
	# test -f $(build_dir)/fs-uae_$(version).orig.tar.gz || cp $(build_dir)/fs-uae-$(version).tar.gz $(build_dir)/fs-uae_$(version).orig.tar.gz
	mv $(build_dir)/fs-uae-$(version).tar.gz $(build_dir)/fs-uae_$(version).orig.tar.gz

	sed -i "s/-0[)] unstable;/-$(debversion)) $(debseries);/g" $(dist_dir)/debian/changelog
	cd $(dist_dir) && dpkg-buildpackage -S -us -uc

deb: debsrc
	# cd $(dist_dir) && fakeroot debian/rules binary
	# mkdir -p dist/$(series)/$(version)
	# mv build/fs-uae_$(version)-*deb dist/$(series)/$(version)/
	cd $(dist_dir) && dpkg-buildpackage -us -uc

windows-dist: distdir
	cd $(dist_dir)/windows && make
	mv $(dist_dir)/fs-uae_*windows* .
	rm -Rf $(dist_dir)

macosx-dist: distdir
	cd $(dist_dir)/macosx && make
	mv $(dist_dir)/fs-uae_*macosx* .
	rm -Rf $(dist_dir)

dist_dir_launcher := fs-uae-launcher-$(version)

debseries := unstable
debversion := $(shell date +"%s")

pubfiles:
	mkdir -p dist

pubfiles-source:
	mkdir -p dist
	cp -a ChangeLog example.conf dist/
	cp -a fs-uae-$(version)/README dist/
	chmod 0644 dist/README
	chmod 0644 dist/ChangeLog
	chmod 0644 dist/example.conf

clean-dist:
	rm -Rf build dist fs-uae-[0-9]* fs-uae_*

clean:
	rm -Rf gen obj
	rm -f fs-uae fs-uae.exe
	rm -f fs-uae-device-helper fs-uae-device-helper.exe

distclean: clean clean-dist
