from enum import StrEnum


class EventName(StrEnum):
    FSAPP_GAMEPAD_NAME = "FSAPP_GAMEPAD_NAME"
    FSAPP_JOYSTICK_NAME = "FSAPP_JOYSTICK_NAME"
    FSAPP_KEYBOARD_NAME = "FSAPP_KEYBOARD_NAME"
    FSAPP_MOUSE_NAME = "FSAPP_MOUSE_NAME"
    SDL_EVENT_GAMEPAD_ADDED = "SDL_EVENT_GAMEPAD_ADDED"
    SDL_EVENT_GAMEPAD_REMAPPED = "SDL_EVENT_GAMEPAD_REMAPPED"
    SDL_EVENT_GAMEPAD_REMOVED = "SDL_EVENT_GAMEPAD_REMOVED"
    SDL_EVENT_JOYSTICK_ADDED = "SDL_EVENT_JOYSTICK_ADDED"
    SDL_EVENT_JOYSTICK_REMOVED = "SDL_EVENT_JOYSTICK_REMOVED"
