#ifndef FSAPP_H
#define FSAPP_H

enum {
    FSAPP_MESSAGE_BEFORE_FIRST = 0x10000,
    FSAPP_MESSAGE_INIT_SDL_GAMEPAD = 0x10001,

    // FIXME: Move somewhere else
    FSEMU_MESSAGE_BEFORE_FIRST = 0x20000,
    FSEMU_MESSAGE_SET_PORT_DEVICE = 0x20001,
};

#endif  // FSAPP_H
