#!/bin/sh
set -e

# FIXME: libiconv (except on macOS) ??

PACKAGE=gettext-0.21
CHECKSUM=c77d0da3102aec9c07f43671e60611ebff89a996ef159497ce8e59d075786b12
REVISION=0

. fsdeps/dep.sh

# if test -e $PREFIX/installed/$PACKAGE ; then
# if [ "$REINSTALL" != "1" ]; then
# echo "$PACKAGE is already installed"
# exit 0
# fi
# fi

python3 fsdeps/download.py \
https://ftp.gnu.org/pub/gnu/gettext/$PACKAGE.tar.gz \
sha256:$CHECKSUM

rm -Rf fsdeps/_build && mkdir fsdeps/_build && cd fsdeps/_build
tar xf ../_sources/$PACKAGE.tar.gz
cd $PACKAGE

# ./configure --prefix=$PREFIX \
# --disable-java
cd gettext-runtime
./configure --prefix=$PREFIX \
--disable-csharp \
--disable-java
make
make install

# mkdir -p $PREFIX/installed
# touch $PREFIX/installed/$PACKAGE
touch $INSTALLED
