# Intended for sourcing by other shell scripts
# This file is automatically generated by fs-package

. fsdeps/env.sh
. fsdeps/system.sh

export PREFIX="$FSDEPS_PREFIX"
export REINSTALL="$FSDEPS_REINSTALL"
export INSTALLED="$PREFIX/installed/$PACKAGE-$REVISION"

mkdir -p $PREFIX/installed

if test -e $INSTALLED ; then
if [ "$REINSTALL" != "1" ]; then
echo "$INSTALLED"
exit 0
fi
fi

echo
echo $PACKAGE
