# Intended for sourcing by other shell scripts
# This file is automatically generated by fs-package

case "`uname`" in
    Linux*)  SYSTEM=Linux;;
    Darwin*) SYSTEM=macOS;;
    MINGW*)  SYSTEM=Windows;;
    *)       SYSTEM=Unknown;;
esac
