#!/usr/bin/env python3

import os


def main() -> None:
    with open("od-fs/python/uae/configurations/a500.py", "r") as f:
        lines = f.readlines()

    names: list[str] = []
    for line in lines:
        line.strip()
        if not line or line.startswith('"') or line.startswith(";"):
            continue
        name = line.split("=", 1)[0].strip()
        names.append(name)

    with open("od-fs/python/uae/configkey.py", "w") as f:
        f.write("#!/usr/bin/env python3\n")
        f.write(f"# Generated by {os.path.basename(__file__)}\n")
        f.write("\n")

        f.write("from enum import StrEnum\n")
        f.write("\n")
        f.write("\n")
        f.write("class ConfigKey(StrEnum):\n")
        for name in sorted(names):
            key = name.upper().replace(".", "_").replace("-", "_")
            if key[0] in "0123456789":
                key = "_" + key
            f.write(f'    {key} = "{name}"\n')


if __name__ == "__main__":
    main()
