#!/usr/bin/env python3

import os


def main() -> None:
    enum = True

    with open("inputevents.def", "r") as f:
        lines = f.readlines()

    names: list[str] = []
    for line in lines:
        line.strip()
        if line.startswith("DEFEVENT"):
            name = line.split("(", 1)[1].split(",", 1)[0].strip()
            names.append(name)
            print(name)

    with open("od-fs/python/uae/inputevent.py", "w") as f:
        f.write("#!/usr/bin/env python3\n")
        f.write(f"# Generated by {os.path.basename(__file__)}\n")
        f.write("\n")

        if enum:
            f.write("from enum import IntEnum\n")
            f.write("\n")
            f.write("\n")
            f.write("class InputEvent(IntEnum):\n")
        for i, name in enumerate(names):
            if enum:
                f.write(f"    {name} = {i + 1}\n")
            else:
                f.write(f"INPUTDEVICE_{name} = {i}\n")


if __name__ == "__main__":
    main()
