#ifndef FSEMU_ALL_H_
#define FSEMU_ALL_H_

#include "fsemu/fsemu-audio-alsa.h"
#include "fsemu/fsemu-audio-buffer.h"
#include "fsemu/fsemu-audio.h"
#include "fsemu/fsemu-config.h"
#include "fsemu/fsemu-events.h"
#include "fsemu/fsemu-font.h"
#include "fsemu/fsemu-frame.h"
#include "fsemu/fsemu-gamemode.h"
#include "fsemu/fsemu-gui.h"
#include "fsemu/fsemu-image.h"
#include "fsemu/fsemu-inifile.h"
#include "fsemu/fsemu-input.h"
#include "fsemu/fsemu-keyboard.h"
#include "fsemu/fsemu-layout.h"
#include "fsemu/fsemu-log.h"
#include "fsemu/fsemu-mouse.h"
#include "fsemu/fsemu-perfgui.h"
#include "fsemu/fsemu-quit.h"
#include "fsemu/fsemu-sdlaudio.h"
#include "fsemu/fsemu-sdlinput.h"
#include "fsemu/fsemu-sdlvideo.h"
#include "fsemu/fsemu-sdlwindow.h"
#include "fsemu/fsemu-thread.h"
#include "fsemu/fsemu-time.h"
#include "fsemu/fsemu-titlebar.h"
#include "fsemu/fsemu-types.h"
#include "fsemu/fsemu-util.h"
#include "fsemu/fsemu-video.h"
#include "fsemu/fsemu-window.h"
#include "fsemu/fsemu-xmlshader.h"

#endif  // FSEMU_ALL_H_
