name: Build

on:
  push:
    branches:
      - master
      - dev
      - stable
  pull_request:
    branches:
      - master
      - dev
      - stable

jobs:
  Linux_x86-64:
    runs-on: ubuntu-18.04

    steps:
    - name: Install deb packages
      run: >-
        sudo apt install
        dos2unix
        gettext
        intltool
        libao-dev
        libasound2-dev
        libevdev-dev
        libgbm-dev
        libgl-dev
        libglu-dev
        libopenal-dev
        libpulse-dev
        libudev-dev
        libusb-1.0-0-dev
        libx11-dev
        libx11-xcb-dev
        libxcb1-dev
        libxcb-glx0-dev
        libxcb-icccm4-dev
        libxcb-image0-dev
        libxcb-keysyms1-dev
        libxcb-randr0-dev
        libxcb-render-util0-dev
        libxcb-shape0-dev
        libxcb-shm0-dev
        libxcb-sync0-dev
        libxcb-xfixes0-dev
        libxcb-xinerama0-dev
        libxcursor-dev
        libxext-dev
        libxfixes-dev
        libxi-dev
        libxinerama-dev
        libxrandr-dev
        libxrender-dev
        x11proto-dev

    - name: Install pip packages
      run: |
        sudo python3 -m pip install -U pip setuptools
        sudo python3 -m pip install -U meson ninja

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache dependencies
      uses: actions/cache@v2
      id: fsdeps_cache
      with:
        path: fsdeps/_prefix
        key: fsdeps_${{ hashFiles('fsdeps/**/*') }}_${{ runner.os }}

    - name: Build dependencies
      if: steps.fsdeps_cache.outputs.cache-hit != 'true'
      run: fsdeps/make

    - name: Update version
      run: fsbuild/version --update --auto

    - name: Bootstrap
      run: fsdeps/use fsbuild/bootstrap

    - name: Configure
      run: fsdeps/use fsbuild/configure

    - name: Make
      run: fsdeps/use fsbuild/make

    - name: Bundle
      run: fsdeps/use fsbuild/bundle

    - name: Archive
      run: fsbuild/archive

    - uses: actions/upload-artifact@v2
      with:
        name: Linux_x86-64

        path: fsbuild/_dist/*

    - name: Upload build to Dropbox folder
      if: >-
        github.ref == 'refs/heads/master' ||
        github.ref == 'refs/heads/dev' ||
        github.ref == 'refs/heads/stable'
      run: |
        python3 -m pip install dropbox
        fsbuild/upload
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}

  macOS_x86-64:
    runs-on: macos-10.15

    steps:
    - name: Install brew packages
      run: brew install autoconf automake dos2unix meson

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache dependencies
      uses: actions/cache@v2
      id: fsdeps_cache
      with:
        path: fsdeps/_prefix
        key: fsdeps_${{ hashFiles('fsdeps/**/*') }}_${{ runner.os }}

    - name: Build dependencies
      if: steps.fsdeps_cache.outputs.cache-hit != 'true'
      run: fsdeps/make

    - name: Update version
      run: fsbuild/version --update --auto

    - name: Bootstrap
      run: fsdeps/use fsbuild/bootstrap

    - name: Configure
      run: fsdeps/use fsbuild/configure

    - name: Make
      run: fsdeps/use fsbuild/make

    - name: Bundle
      run: fsbuild/bundle

    - name: Prepare signing certificate
      run: |
        echo $SIGNING_CERTIFICATE_P12_DATA | base64 --decode > certificate.p12
        security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security import certificate.p12 -k build.keychain -P $SIGNING_CERTIFICATE_PASSWORD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD build.keychain
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.MACOS_CERTIFICATE_P12_DATA }}
        SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}

    - name: Sign
      run: fsbuild/sign

    - name: Notarize
      run: fsbuild/notarize
      env:
        NOTARIZATION_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
        NOTARIZATION_PROVIDER: ${{ secrets.MACOS_NOTARIZATION_PROVIDER }}
        NOTARIZATION_USERNAME: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}

    - name: Archive
      run: fsbuild/archive

    - uses: actions/upload-artifact@v2
      with:
        name: macOS_x86-64
        path: fsbuild/_dist/*

    - name: Upload build to Dropbox folder
      if: >-
        github.ref == 'refs/heads/master' ||
        github.ref == 'refs/heads/dev' ||
        github.ref == 'refs/heads/stable'
      run: |
        python3 -m pip install dropbox
        fsbuild/upload
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}

  Windows_x86-64:
    runs-on: windows-2016

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          autoconf
          automake
          base-devel
          gettext
          git
          libtool
          make
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-icoutils
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-openal
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python2
          unzip
          zip

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache dependencies
      uses: actions/cache@v2
      id: fsdeps_cache
      with:
        path: fsdeps/_prefix
        key: fsdeps_${{ hashFiles('fsdeps/**/*') }}_${{ runner.os }}

    - name: Build dependencies
      if: steps.fsdeps_cache.outputs.cache-hit != 'true'
      run: fsdeps/make

    - name: Update version
      run: fsbuild/version --update --auto

    - name: Bootstrap
      run: fsdeps/use fsbuild/bootstrap

    - name: Configure
      run: fsdeps/use fsbuild/configure

    - name: Make
      run: fsdeps/use fsbuild/make

    - name: Bundle
      run: fsbuild/bundle

    - name: Archive
      run: fsbuild/archive

    - uses: actions/upload-artifact@v2
      with:
        name: Windows_x86-64
        path: fsbuild/_dist/*

    - name: Upload build to Dropbox folder
      if: >-
        github.ref == 'refs/heads/master' ||
        github.ref == 'refs/heads/dev' ||
        github.ref == 'refs/heads/stable'
      run: |
        python3 -m pip install dropbox
        fsbuild/upload
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
