#!/bin/sh
set -e

. fsbuild/common.inc.sh

mkdir -p fsbuild/_dist

cd fsbuild/_build

if [ "$SYSTEM" = "Windows" ]; then
ARCHIVE=${PACKAGE}_${VERSION}_${OS}_${ARCH}.zip
zip -r ../_dist/$ARCHIVE ${PACKAGE}
else
ARCHIVE=${PACKAGE}_${VERSION}_${OS}_${ARCH}.tar.xz
tar cfJv ../_dist/$ARCHIVE ${PACKAGE}
fi

echo
echo fsbuild/_dist/$ARCHIVE
