# Intended for sourcing by other shell scripts
# This file is automatically generated by fs-package

. ./PACKAGE.FS

if [ "`uname`" = "Linux" ]; then
OS=Linux
SYSTEM=Linux
ARCH=x86-64
elif [ "`uname`" = "Darwin" ]; then
SYSTEM=macOS
OS=macOS
ARCH=x86-64
elif [ "`uname -o`" = "Msys" ]; then
SYSTEM=Windows
OS=Windows
ARCH=x86-64
fi
