#!/bin/sh
# This file is automatically generated by fs-package

if [ "$SYSTEM_OS" = "macOS" ]; then
if [ -d "$PLUGIN_BINDIR/$PACKAGE_NAME_PRETTY.app" ]; then
echo "App bundle already exists"
else
EXECUTABLE=$PACKAGE_NAME
sh fsbuild/appify.sh $PLUGIN_BINDIR $PACKAGE_NAME_PRETTY \
$EXECUTABLE $PACKAGE_MACOS_BUNDLE_ID
fi
fi

# python3 fsbuild/standalone.py $PLUGIN_BINDIR
LIBGPG_ERROR_CHECK=0 python3 fsbuild/standalone.py $PLUGIN_BINDIR

echo "[plugin]" > $PLUGIN_DIR/Plugin.ini
echo "name = ${plugin}" >> $PLUGIN_DIR/Plugin.ini
echo "version = ${version}" >> $PLUGIN_DIR/Plugin.ini
unix2dos $PLUGIN_DIR/Plugin.ini

echo $PACKAGE_VERSION > $PLUGIN_DIR/Version.txt
unix2dos $PLUGIN_DIR/Version.txt

if [ -d $PLUGIN_BINDIR ]; then
echo $PACKAGE_VERSION > $PLUGIN_BINDIR/Version.txt
unix2dos $PLUGIN_BINDIR/Version.txt
fi
