# Intended for sourcing by other shell scripts
# This file is automatically generated by fs-package

case "`uname`" in
    Linux*)  SYSTEM_OS=Linux;;
    Darwin*) SYSTEM_OS=macOS;;
    MINGW*)  SYSTEM_OS=Windows;;
    *)       SYSTEM_OS=Unknown;;
esac

# FIXME: Remove hardcoded value
SYSTEM_ARCH=x86-64

if [ $SYSTEM_OS = "Windows" ]; then
SYSTEM_EXE=.exe
SYSTEM_DLL=.dll
else
SYSTEM_EXE=
SYSTEM_DLL=.so
fi

# FIXME: Deprecated alias
SYSTEM=$SYSTEM_OS
