#!/usr/bin/env python3

import os

import dropbox
import requests

package_data = {}
with open("PACKAGE.FS", "r") as f:
    for line in f:
        try:
            key, value = line.strip().split("=", 1)
            package_data[key] = value
        except ValueError:
            pass


def execute_discord_webhook(name, link):
    webhook_url = os.getenv("DISCORD_WEBHOOK_URL")
    if not webhook_url:
        return
    content = (
        f"`{name}` was built and uploaded to a Dropbox "
        f"[shared folder]({link})"
    )
    requests.post(webhook_url, {"content": content, "username": "Builder"})


def upload(dbx, package, version, path):
    print("Upload", path)
    name = os.path.basename(path)
    assert package in name
    assert version in name
    dst = f"/Builds/CI/{package}/{version}/{name}"
    with open(path, "rb") as f:
        dbx.files_upload(f.read(), dst)
    print("Uploaded ->", dst)
    if os.getenv("DISCORD_WEBHOOK_URL"):
        result = dbx.sharing_list_shared_links(f"/Builds/CI/{package}")
        link = result.links[0].url
        execute_discord_webhook(name, link)


def main():
    dist_dir = "fsbuild/_dist"
    upload_items = os.listdir(dist_dir)
    # Require there to be exactly one dist file for now
    assert len(upload_items) == 1

    dbx = dropbox.Dropbox(os.getenv("DROPBOX_ACCESS_TOKEN"))
    package = package_data["PACKAGE_NAME_PRETTY"]
    version = package_data["PACKAGE_VERSION"]
    for item in upload_items:
        upload(dbx, package, version, os.path.join(dist_dir, item))


if __name__ == "__main__":
    main()
